data_dir_in: "/mnt/c/Users/Julian/Research/Pipeline/data/GGR2020_subset_small/"
db_dir: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/"
image_dirname: "images"
annot_dirname: "annots"
import_out_file: "image_data.json"

dt_dir: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/detector/"
ground_truth_csv: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/GZCD_Cleaned.csv"
model_version : "yolov10l"
annots_filename: "pred_annots_"
annots_filtered_filename: "filtered_pred_annots_"

si_dir: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/species_identifier/"
predictions_dir: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/species_identifier/predictions/"
si_out_file_end: "_bioCLIP_predictions.csv"

vc_dir: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/viewpoint_classifier/"
vc_model_checkpoint: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/VC_july_22_tf_efficientnet_b4_ns_5-3.pth"
vc_out_file: "output_with_viewpoint.csv"

cac_dir: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/ca_classifier/"
cac_model_checkpoint: "/mnt/c/Users/Julian/Research/Pipeline/data/test_dataset/best_july_8_cuda_extended_aug_sample_annot_classifier.pth"
cac_out_file: "final_output_with_softmax_and_census.csv"
