data_dir_in: "images/"
db_dir: "test_dataset/"
image_dirname: "images"
annot_dirname: "annots"
import_out_file: "image_data.json"

dt_dir: "test_dataset/detector/"
ground_truth_csv: "test_dataset/annotations.csv"
model_version: "yolov10l"
annots_filename: "pred_annots_"
annots_filtered_filename: "filtered_pred_annots_"

si_dir: "test_dataset/species_identifier/"
predictions_dir: "test_dataset/species_identifier/predictions/"
si_out_file_end: "_bioCLIP_predictions.csv"

vc_dir: "test_dataset/viewpoint_classifier/"
vc_model_checkpoint: "test_dataset/your_viewpoint_classifier.pth"
vc_out_file: "output_with_viewpoint.csv"

cac_dir: "test_dataset/ca_classifier/"
cac_model_checkpoint: "test_dataset/your_ca_classifier.pth"
cac_out_filename: "final_output_with_softmax_and_census"

fs_dir: "test_dataset/frame_sampling/"
fs_out_stage1_json_file: "out1.json"
fs_out_final_json_file: "out2.json"

mid_dir: "test_dataset/miew_id/"
mid_model_url: "conservationxlabs/miewid-msv3"
mid_out_json_file: "miewid_output.json"
mid_out_pkl_file: "miewid_output.pickle"
