data_dir_in: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/GGR2020_subset/"
db_dir: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/"
image_dirname: "images"
annot_dirname: "annots"
import_out_file: "image_data.json"

dt_dir: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/detector/"
ground_truth_csv: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/posttt_your_file.csv"
model_version : "yolov10l"
annots_filename: "pred_annots_"
annots_filtered_filename: "filtered_pred_annots_"

si_dir: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/test_dataset/species_identifier/"
predictions_dir: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/test_dataset/species_identifier/predictions/"
si_out_file_end: "_bioCLIP_predictions.csv"

vc_dir: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/test_dataset/viewpoint_classifier/"
vc_model_checkpoint: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/test_dataset/drone_VC_july_18_tf_efficientnet_b4_ns_8.pth"
vc_out_file: "output_with_viewpoint.csv"

cac_dir: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/test_dataset/ca_classifier/"
cac_model_checkpoint: "/Users/jaeseok/Developer/GGR/Imageomics-Species-ReID/test_dataset/test_dataset/best_july_8_cuda_extended_aug_sample_annot_classifier.pth"
cac_out_file: "final_output_with_softmax_and_census.csv"
