data_dir_in: "GGR_video_test"
data_video: True
db_dir: "test_dataset/"
image_dirname: "images"
video_dirname: "videos"
annot_dirname: "annots"
image_out_file: "image_data.json"
video_out_file: "video_data.json"

dt_dir: "test_dataset/detector/"
ground_truth_csv: "test_dataset/annotations.csv"
model_version: "yolov10l"
annots_filename: "pred_annots_"
annots_filtered_filename: "filtered_pred_annots_"

si_dir: "test_dataset/species_identifier/"
predictions_dir: "test_dataset/species_identifier/predictions/"
si_out_file_end: "_bioCLIP_predictions.csv"

vc_dir: "test_dataset/viewpoint_classifier/"
vc_model_checkpoint: "test_dataset/viewpoint_trained_model.pth"
vc_out_file: "output_with_viewpoint.csv"

cac_dir: "test_dataset/ca_classifier/"
cac_model_checkpoint: "test_dataset/best_july_8_cuda_extended_aug_sample_annot_classifier.pth"
cac_out_filename: "final_output_with_softmax_and_census"

fs_dir: "test_dataset/frame_sampling/"
fs_out_stage1_json_file: "stage1_fs_output.json"
fs_out_final_json_file: "final_fs_output.json"

mid_dir: "test_dataset/miew_id/"
mid_model_url: "conservationxlabs/miewid-msv3"
mid_out_file: "miewid_output.pickle"

lca_dir: "test_dataset/lca/"
lca_db_dir: "db/"
lca_log_file: "lca_logs.log"
lca_verifier_probs: "verifier_probs.json"