channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal>=8.4.4
  - pip
  - python==3.11
  - albumentations>=2.0.4
  - zbar
  - conda-forge::zbar-py
  - nvidia::cuda
  - libtiff=4.5.1
  - pip:
    #  at the time of writing - 7. Feb 24 - pysam on bioconda will require
    #  a lower python version than snakemake, install pysam
    #  using pip
    - oauthlib ==3.2.2
    - pillow ==10.3.0
    - pysam ==0.22
    - qreader ==3.13
    - requests_oauthlib ==2.0.0
    - six ==1.16.0
    - geopandas ==1.0.1
    - scikit-learn ==1.5.1
    - timm ==1.0.7
    - transformers ==4.49.0
    - lap >=0.5.12
    - pyzbar >= 0.1.9
    - gradio
    - git+https://github.com/AidanWestphal/pybioclip
    - -e . # INSTALLS GGR ITSELF AS A MODULE IN EDIT MODE