channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal >=8.4.4
  - python ==3.11
  - pip:
    #  at the time of writing - 7. Feb 24 - pysam on bioconda will require
    #  a lower python version than snakemake, install pysam
    #  using pip
    - oauthlib ==3.2.2
    - pillow ==10.3.0
    - pysam ==0.22
    - qreader ==3.13
    - requests_oauthlib ==2.0.0
    - six ==1.16.0
    - geopandas ==1.0.1
    - scikit-learn ==1.5.1
    - albumentations ==1.4.11
    - timm ==1.0.7

# TODO: PYZBAR AND UPDATED VERSION OF ALBUMENTATIONS TO 2.*