in_json_path: "C:\\Users\\jmani\\Downloads\\image_data.json"
out_json_path: "C:\\Users\\jmani\\Local Documents\\GGR\\VARe-ID\\loc_by_uuid.json"
proj_path: "C:\\Users\\jmani\\Local Documents\\GGR\\VARe-ID"