import os
import json
import argparse
import yaml
import matplotlib.pyplot as plt
import seaborn as sns

def plot_learning_curves(checkpoint_dir, output_dir, run_name, task):
    sns.set_theme(style="whitegrid")
    models = ['base', 'global', 'mil', 'encoder']
    names = ['CNN (EfficientNet)', 'Global (DINO CLS)', 'AB-MIL', 'Transformer MIL']
    colors = ['#e63946', '#f4a261', '#2a9d8f', '#264653']
    
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    found_any = False
    
    for mod, name, color in zip(models, names, colors):
        # We look for the exact names generated by the training scripts
        target_name = f"{mod}_{run_name}"
        path = os.path.join(checkpoint_dir, f"history_{task}_{target_name}.json")
        
        if not os.path.exists(path):
            print(f"Warning: Could not find {path}")
            continue
            
        found_any = True
        with open(path, 'r') as f:
            history = json.load(f)
            
        epochs = range(1, len(history['train_loss']) + 1)
        axes[0].plot(epochs, history['train_loss'], label=name, color=color, linewidth=2)
        axes[1].plot(epochs, history['val_loss'], label=name, color=color, linewidth=2)
        axes[2].plot(epochs, history['val_f1'], label=name, color=color, linewidth=2)

    if not found_any:
        print(f"No history files found for task '{task}' with run_name '{run_name}'. Aborting plot.")
        return

    axes[0].set_title(f'{task.upper()}: Training Loss', fontsize=14, fontweight='bold')
    axes[1].set_title(f'{task.upper()}: Validation Loss', fontsize=14, fontweight='bold')
    axes[2].set_title(f'{task.upper()}: Validation Macro F1', fontsize=14, fontweight='bold')
    
    for ax in axes:
        ax.set_xlabel('Epochs', fontsize=12)
        ax.legend()
        
    plt.tight_layout()
    out_path = os.path.join(output_dir, f'learning_curves_{task}_{run_name}.pdf')
    plt.savefig(out_path, dpi=300)
    print(f"Saved {out_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=str, default='agesex_dino.yaml', help='Path to yaml config')
    parser.add_argument('--checkpoint_dir', type=str, required=True, help='Where the .json files live')
    parser.add_argument('--output_dir', type=str, default='./eval_results', help='Where to save the graphs')
    args = parser.parse_args()
    
    with open(args.config, 'r') as f:
        config = yaml.safe_load(f)
    run_name = config.get('run_name', 'default')
    
    # Create an experiment-specific output directory
    exp_out_dir = os.path.join(args.output_dir, run_name)
    os.makedirs(exp_out_dir, exist_ok=True)
    
    plot_learning_curves(args.checkpoint_dir, exp_out_dir, run_name, 'age')
    plot_learning_curves(args.checkpoint_dir, exp_out_dir, run_name, 'sex')